package com.mokeu.ga;

public final class GAParameters{
	public final static String PROTOCOL_VERSION="v",
			TRACKING_ID="tid",
			ANONYMIZE_IP="aip",
			QUEUE_TIME="qt",
			CACHE_BUSTER="z",
			CLIENT_ID="cid",
			SESSION_CONTROL="sc",
			DOCUMENT_REFERRER="dr",
			CAMPAIGN_NAME="cn",
			CAMPAIGN_SOURCE="cs",
			CAMPAIGN_MEDIUM="cm",
			CAMPAIGN_KEYWORD="ck",
			DOCUMENT_HOST_NAME="dh",
			DOCUMENT_PATH="dp",
			DOCUMENT_TITLE="dt",
			HIT_TYPE="t",
			CONTENT_DESCRIPTION="cd",
			VERSION = "v",
			JAVA_ENABLED="je",
			USER_LANGUAGE="ul",
			SCREEN_RESOLUTION="sr",
			APP_VERSION = "av",
			APP_NAME="an",
			EVENT_CATEGORY = "ec",
			EVENT_ACTION="ea",
			EVENT_LABEL="el",
			EVENT_VALUE="ev",
			DOCUMENT_LOCATION_URL = "dl",
			SOCIAL_NETWORK="sn",
			SOCIAL_ACTION="sa",
			SOCIAL_ACTION_TARGET="st",
			USER_TIMING_CATEGORY="utc",
			USER_TIMING_VARIABLE_NAME="utv",
			USER_TIMING_TIME="utt",
			USER_TIMING_LABEL="utl",
			PAGE_LOAD_TIME="plt",
			DNS_TIME="dns",
			PAGE_DOWNLOAD_TIME="pdt",
			REDIRECT_RESPONSE_TIME="rrt",
			SERVER_RESPONSE_TIME="srt",
			EXCEPTION_DESCRIPTION="exd",
			IS_EXCEPTOIN_FATAL="exf",
			CUSTOM_DIMENSION="cd",
			CUSTOM_METRIC="cm";
			
}