package com.mokeu.ga;

public final class GAParameters{
	public final static String PROTOCOL_VERSION="v",
			TRACKING_ID="tid",
			ANONYMIZE_IP="aip",
			QUEUE_TIME="qt",
			CACHE_BUSTER="z",
			CLIENT_ID="cid",
			SESSION_CONTROL="sc",
			DOCUMENT_REFERRER="dr",
			CAMPAIGN_NAME="cn",
			CAMPAIGN_SOURCE="cs",
			CAMPAIGN_MEDIUM="cm",
			CAMPAIGN_KEYWORD="ck",
			DOCUMENT_HOST_NAME="dh",
			DOCUMENT_PATH="dp",
			DOCUMENT_TITLE="dt",
			HIT_TYPE="t",
			CONTENT_DESCRIPTION="cd",
			VERSION = "v",
			JAVA_ENABLED="je",
			USER_LANGUAGE="ul",
			SCREEN_RESOLUTION="sr",
			APP_VERSION = "av",
			APP_NAME="an",
			EVENT_CATEGORY = "ec",
			EVENT_ACTION="ea",
			EVENT_LABEL="el",
			EVENT_VALUE="ev";
}